apiVersion: v1
kind: Service
metadata:
  name: argocd-hw-service
  namespace: default
spec:
  selector: 
    app: argocd-hw-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30101
  type: NodePort  
